steps:

# Terraform Init
- name: hashicorp/terraform:1.6.6
  dir: env/dev
  entrypoint: sh
  args:
    - -c
    - |
      terraform init

# Terraform Plan
- name: hashicorp/terraform:1.6.6
  dir: env/dev
  entrypoint: sh
  args:
    - -c
    - |
      terraform plan

# Terraform Apply
- name: hashicorp/terraform:1.6.6
  dir: env/dev
  entrypoint: sh
  args:
    - -c
    - |
      terraform apply -auto-approve

options:
 logging: CLOUD_LOGGING_ONLY